# Generated by Django 6.0.2 on 2026-02-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_product_image_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
